// SPDX-License-Identifier: GPL-2.0+
/*
 * Copyright (c) 2020- Aodzip
 * All rights reserved.
 * Author: Aodzip <aodzip@gmail.com>
 */
#ifndef __SUN6I_DPHY_REG_H__
#define __SUN6I_DPHY_REG_H__

#include <linux/kernel.h>

#define DPHY_OFFSET 0x2000

#define DPHY_CTL_REG (DPHY_OFFSET + 0x000)
#define DPHY_CTL_REG_LANE_NUM_SHIFT 4
#define DPHY_CTL_REG_LANE_NUM GENMASK(DPHY_CTL_REG_LANE_NUM_SHIFT + 1, DPHY_CTL_REG_LANE_NUM_SHIFT)
#define DPHY_CTL_REG_EN_SHIFT 0
#define DPHY_CTL_REG_EN BIT(DPHY_CTL_REG_EN_SHIFT)
/* DPHY_CTL_REG */

#define DPHY_RX_CTL_REG (DPHY_OFFSET + 0x008)
#define DPHY_RX_CTL_REG_DBC_EN_SHIFT 31
#define DPHY_RX_CTL_REG_RX_CLK_FORCE_SHIFT 24
#define DPHY_RX_CTL_REG_RX_DATA_FORCE_SHIFT 20

#define DPHY_RX_CTL_REG_DBC_EN BIT(DPHY_RX_CTL_REG_DBC_EN_SHIFT)
#define DPHY_RX_CTL_REG_RX_CLK_FORCE BIT(DPHY_RX_CTL_REG_RX_CLK_FORCE_SHIFT)
#define DPHY_RX_CTL_REG_RX_DATA_FORCE GENMASK(DPHY_RX_CTL_REG_RX_DATA_FORCE_SHIFT + 3, DPHY_RX_CTL_REG_RX_DATA_FORCE_SHIFT)
/* DPHY_RX_CTL_REG */

#define DPHY_RX_TIME0_REG (DPHY_OFFSET + 0x030)
#define DPHY_RX_TIME0_REG_HSRX_SYNC_ERR_TO_SHIFT 24
#define DPHY_RX_TIME0_REG_HSRX_CLK_MISS_SHIFT 16
#define DPHY_RX_TIME0_REG_LPRX_TO_SHIFT 8
#define DPHY_RX_TIME0_REG_HSRX_SYNC_ERR_TO_EN_SHIFT 5
#define DPHY_RX_TIME0_REG_HSRX_CLK_MISS_EN_SHIFT 4
#define DPHY_RX_TIME0_REG_FREQ_CNT_EN_SHIFT 1
#define DPHY_RX_TIME0_REG_LPRX_TO_EN_SHIFT 0

#define DPHY_RX_TIME0_REG_HSRX_SYNC_ERR_TO GENMASK(31, DPHY_RX_TIME0_REG_HSRX_SYNC_ERR_TO_SHIFT)
#define DPHY_RX_TIME0_REG_HSRX_CLK_MISS GENMASK(23, DPHY_RX_TIME0_REG_HSRX_CLK_MISS_SHIFT)
#define DPHY_RX_TIME0_REG_LPRX_TO GENMASK(15, DPHY_RX_TIME0_REG_LPRX_TO_SHIFT)
#define DPHY_RX_TIME0_REG_HSRX_SYNC_ERR_TO_EN BIT(DPHY_RX_TIME0_REG_HSRX_SYNC_ERR_TO_EN_SHIFT)
#define DPHY_RX_TIME0_REG_HSRX_CLK_MISS_EN BIT(DPHY_RX_TIME0_REG_HSRX_CLK_MISS_EN_SHIFT)
#define DPHY_RX_TIME0_REG_FREQ_CNT_EN BIT(DPHY_RX_TIME0_REG_FREQ_CNT_EN_SHIFT)
#define DPHY_RX_TIME0_REG_LPRX_TO_EN BIT(DPHY_RX_TIME0_REG_LPRX_TO_EN_SHIFT)
/* DPHY_RX_TIME0_REG */

#define DPHY_RX_TIME1_REG (DPHY_OFFSET + 0x034)
#define DPHY_RX_TIME1_REG_RX_DLY_SHIFT 20
#define DPHY_RX_TIME1_REG_LPRX_ULPS_WP_SHIFT 0
#define DPHY_RX_TIME1_REG_RX_DLY GENMASK(31, DPHY_RX_TIME1_REG_RX_DLY_SHIFT)
#define DPHY_RX_TIME1_REG_LPRX_ULPS_WP GENMASK(19, DPHY_RX_TIME1_REG_LPRX_ULPS_WP_SHIFT)
/* DPHY_RX_TIME1_REG */

#define DPHY_RX_TIME2_REG (DPHY_OFFSET + 0x038)
#define DPHY_RX_TIME2_REG_HSRX_ANA1_SET_SHIFT 8
#define DPHY_RX_TIME2_REG_HSRX_ANA0_SET_SHIFT 0
#define DPHY_RX_TIME2_REG_HSRX_ANA1_SET GENMASK(15, DPHY_RX_TIME2_REG_HSRX_ANA1_SET_SHIFT)
#define DPHY_RX_TIME2_REG_HSRX_ANA0_SET GENMASK(7, DPHY_RX_TIME2_REG_HSRX_ANA0_SET_SHIFT)
/* DPHY_RX_TIME2_REG */

#define DPHY_RX_TIME3_REG (DPHY_OFFSET + 0x040)
#define DPHY_RX_TIME3_REG_LPRST_DLY_SHIFT 16
#define DPHY_RX_TIME3_REG_LPRST_DLY GENMASK(31, DPHY_RX_TIME3_REG_LPRST_DLY_SHIFT)
#define DPHY_RX_TIME3_REG_FREQ_CNT_SHIFT 0
#define DPHY_RX_TIME3_REG_FREQ_CNT GENMASK(15, DPHY_RX_TIME3_REG_FREQ_CNT_SHIFT)
/* DPHY_RX_TIME3_REG */

#define DPHY_ANA0_REG (DPHY_OFFSET + 0x04C)
#define DPHY_ANA0_REG_PWS_SHIFT 31
#define DPHY_ANA0_REG_DMPC_SHIFT 28
#define DPHY_ANA0_REG_DMP_SHIFT 24
#define DPHY_ANA0_REG_SLV_SHIFT 12
#define DPHY_ANA0_REG_SFB_SHIFT 2

#define DPHY_ANA0_REG_PWS BIT(DPHY_ANA0_REG_PWS_SHIFT)
#define DPHY_ANA0_REG_DMPC BIT(DPHY_ANA0_REG_DMPC_SHIFT)
#define DPHY_ANA0_REG_DMP GENMASK(27, DPHY_ANA0_REG_DMP_SHIFT)
#define DPHY_ANA0_REG_SLV GENMASK(14, DPHY_ANA0_REG_SLV_SHIFT)
#define DPHY_ANA0_REG_SFB GENMASK(3, DPHY_ANA0_REG_SFB_SHIFT)
/* DPHY_ANA0_REG */

#define DPHY_ANA1_REG (DPHY_OFFSET + 0x050)
#define DPHY_ANA1_REG_SVTT_SHIFT 24
#define DPHY_ANA1_REG_SVTT GENMASK(27, DPHY_ANA1_REG_SVTT_SHIFT)
/* DPHY_ANA1_REG */

#define DPHY_ANA2_REG (DPHY_OFFSET + 0x054)
#define DPHY_ANA2_REG_ENIB_SHIFT 1
#define DPHY_ANA2_REG_ENIB BIT(DPHY_ANA2_REG_ENIB_SHIFT)
/* DPHY_ANA2_REG */

#define DPHY_ANA3_REG (DPHY_OFFSET + 0x058)
#define DPHY_ANA3_REG_ENVTTC_SHIFT 27
#define DPHY_ANA3_REG_ENLDOC_SHIFT 25
#define DPHY_ANA3_REG_ENLDOD_SHIFT 24
#define DPHY_ANA3_REG_ENLDOR_SHIFT 18

#define DPHY_ANA3_REG_ENVTTC BIT(DPHY_ANA3_REG_ENVTTC_SHIFT)
#define DPHY_ANA3_REG_ENLDOC BIT(DPHY_ANA3_REG_ENLDOC_SHIFT)
#define DPHY_ANA3_REG_ENLDOD BIT(DPHY_ANA3_REG_ENLDOD_SHIFT)
#define DPHY_ANA3_REG_ENLDOR BIT(DPHY_ANA3_REG_ENLDOR_SHIFT)
/* DPHY_ANA3_REG */

#define DPHY_ANA4_REG (DPHY_OFFSET + 0x05C)
#define DPHY_ANA4_REG_DMPLVC_SHIFT 24
#define DPHY_ANA4_REG_DMPLVD_SHIFT 20
#define DPHY_ANA4_REG_DMPLVC BIT(DPHY_ANA4_REG_DMPLVC_SHIFT)
#define DPHY_ANA4_REG_DMPLVD GENMASK(23, DPHY_ANA4_REG_DMPLVD_SHIFT)
/* DPHY_ANA4_REG */

#endif /* __SUN6I_DPHY_REG_H__ */